### PR TITLE
Fixed docstrings

### LINKED ISSUE #97: Add angle units to doc string
Perhaps angles in degrees or radians should be added to this doc string

https://github.com/fusion-energy/openmc-dagmc-wrapper/blob/3806834e22a96f5cd58d95ff5407e83f25efebae/openmc_dagmc_wrapper/Geometry.py#L18-L20

Elsewhere in the code we use radians

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
Fixes #97

### CODE REVIEW

**Comment by shimwell** [comment]
failing tests are unrelated.

**Review by shimwell — APPROVED** [review]
thanks Remi

**Comment by RemDelaporteMathurin** [comment]
> failing tests are unrelated. I am close to fixing these :-)

Are these tests easy to solve?

I was planning on doing some refactoring but this is not very good practice as tests failing early (here utils) will hide potential bugs...

**Comment by RemDelaporteMathurin** [comment]
Oh it's not just the utils, all the tests are failing! we have no CI 😃

**Pull request merged**
