### PR TITLE
Wrapping dagmc bounding box

### PR DESCRIPTION
**Pull request by shimwell**
This adds a ```corners()``` method to the Geometry class.

```corners``` can be used to find the bounding box coordinates which is often needed for 2d or 3d mesh tallies

This makes use of the ```dagmc-bounding-box``` package

Tests have been added to check the corners are accessible and correct.

Examples have been updated

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
That's really convenient @shimwell . Can the MeshTally tests be modified accordingly then?

**Comment by shimwell** [comment]
> 

I can do that just to simplify things, but I don't think that wouldn't test anything new.

**Comment by shimwell** [comment]
So this helps simplify the user facing workflow a little bit as one less tool is needed by the users.

User facing tools is just a subsection of all the tools available and are in blue on this diagram

neutronics_workflow drawio(5)
.

**Comment by RemDelaporteMathurin** [comment]
> > 
> 
> I can do that just to simplify things, but I don't think that wouldn't test anything new.

I think it would cause, as far as I know, the examples aren't tested in GA or CircleCI. Which means that the integration of this new feature with the Mesh tallies isn't tested.

**Comment by shimwell** [comment]
I've updated the meshtally tests to make use of this and also updated the test in ```tests/test_system/test_system_single_volume.py``` to make use of this new feature

**Comment by shimwell** [comment]
codiga comments are mainly regarding the url download for testing, this is a known problem

**Comment by RemDelaporteMathurin** [comment]
> I've updated the meshtally tests to make use of this and also updated the test in `tests/test_system/test_system_single_volume.py` to make use of this new feature

These tests now fail. Must be due to a missing import

**Comment by shimwell** [comment]
Made some changes, now passing locally

**Comment by RemDelaporteMathurin** [comment]
However this test exists in main https://github.com/fusion-energy/openmc-dagmc-wrapper/blob/3d0f7b8aa1448195d313d345bb0283f508e56368/tests/test_tallies/test_mesh_tally_2d.py#L95

**Comment by shimwell** [comment]
ah was I out of sync with develop, thanks for that merge

**Comment by RemDelaporteMathurin** [comment]
I re-synced the branch with develop with the last commit. The problem came from the fact that #93 wasn't merged in develop but in main that was my mistake sorry about that

**Comment by shimwell** [comment]
I think the docker images building can also be improved. I think this can be fixed by adding docker layer caching to the build docker images script. But perhaps that should be solved that in another PR.

**Comment by shimwell** [comment]
tests are passing, good to merge?

**Comment by RemDelaporteMathurin** [comment]
Sounds good to me!

**Pull request merged**
