### PR TITLE
Fix bounding box tests

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
This PR should fix the current failing tests in master.

Although there is a 404 not found error that needs to be fixed. As if CircleCI wasn't able to access the archives.

Which is weird cause the following works locally:

```python
import urllib.request
from pathlib import Path


if not Path("tests/v0.0.2.tar.gz").is_file():
    url = "https://github.com/fusion-energy/neutronics_workflow/archive/refs/tags/v0.0.2.tar.gz"
    urllib.request.urlretrieve(url, "tests/v0.0.2.tar.gz")
```

### CODE REVIEW

**Comment by shimwell** [comment]
Thanks for this, looks good. feel free to merge when you like

**Comment by RemDelaporteMathurin** [comment]
I don't think this should be merged until that 404 error is fixed cause we don't know for sure it can fix the issue.

**Comment by RemDelaporteMathurin** [comment]
I don't think this should be merged until that 404 error is fixed cause we don't know for sure this fix actually works until the CI works again

**Comment by shimwell** [comment]
Moved tests and functionality to dagmc-bounding-box package so this pr is no longer needed

**Pull request closed without merging**
