### PR TITLE
Major refactoring: moving from one class to an openmc-like architecture

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
Todo:

- [ ] Thoroughly complete the docstrings
- [x] Check coverage (set up a codecov workflow?)

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@Shimwell I think we are already uploading to codecov, just it doesn't seem to comment on the PR

**Comment by Shimwell** [comment]
This is an epic refactoring Remi, thanks so much for this.

**Comment by RemDelaporteMathurin** [comment]
> This is an epic refactoring Remi, thanks so much for this.

image

**Comment by RemDelaporteMathurin** [comment]
@Shimwell I feel like we need to add a test for reflective planes before merging this ... what do you think?

**Comment by Shimwell** [comment]
I wonder, perhaps we could do a 90 degree sector model with a full 360 degree ring source and check the tally is 1/4 of the normal result

**Comment by RemDelaporteMathurin** [comment]
> I wonder, perhaps we could do a 90 degree sector model with a full 360 degree ring source and check the tally is 1/4 of the normal result

That could work yeah

**Comment by Shimwell** [comment]
I think we have a issue with the 2d mesh for sector models, this is a 360 degree ring source on a sector model. The mesh aspect ratio ends up a little wrong. I guess the number of pixels is the same in each dimension even if the geometry is larger in some dimensions
neutron_effective_dose_on_2D_mesh_xy
,

**Comment by Shimwell** [comment]
The model used in the examples is a 90 degree sector model with a graveyard cell. However the graveyard can be removed using 

```
pip install remove-dagmc-tags 
remove-dagmc-tags -i dagmc.h5m -o=dagmc_no_grave_yard.h5m -t graveyard
```

**Comment by RemDelaporteMathurin** [comment]
> I think we have a issue with the 2d mesh for sector models, this is a 360 degree ring source on a sector model. The mesh aspect ratio ends up a little wrong. I guess the number of pixels is the same in each dimension even if the geometry is larger in some dimensions
> neutron_effective_dose_on_2D_mesh_xy
> ,

I don't really understand what I'm looking at here. Maybe this can be fixed in another PR?

**Comment by Shimwell** [comment]
tests pass locally over here

**Pull request merged**
